# Generated by Django 2.0.6 on 2018-12-08 18:46

from django.db import migrations, models
import django.utils.timezone
import m_events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('thumbnail', models.FileField(default='events_thumbnails/_default.svg', upload_to=m_events.models.RandomFileName('events_thumbnails/'))),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
