# Generated by Django 2.0.6 on 2018-12-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='event',
            name='text',
        ),
    ]
