# Generated by Django 2.0.6 on 2018-12-08 19:01

from django.db import migrations, models
import django.db.models.deletion
import m_events.models


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0002_auto_20181208_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('TXT', 'Text'), ('FLE', 'File')], default='TXT', max_length=3)),
                ('file', models.FileField(default='events_data/_default.svg', upload_to=m_events.models.RandomFileName('events_data/'))),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_events.Event'),
        ),
    ]
