# Generated by Django 2.0.6 on 2018-12-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0003_auto_20181208_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='text',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
