# Generated by Django 2.0.6 on 2018-12-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0005_auto_20181208_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MEM', 'Meme'), ('MUS', 'Music'), ('POL', 'Politics'), ('SPT', 'Sport'), ('ART', 'Art')], default='MEM', max_length=3),
        ),
    ]
