# Generated by Django 2.0.6 on 2018-12-09 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0006_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accept_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='accepted_by',
            field=models.IntegerField(default=1),
        ),
    ]
