# Generated by Django 2.0.6 on 2018-12-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0007_auto_20181209_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MEM', 'Meme'), ('POL', 'Politics'), ('SPT', 'Sport'), ('ART', 'Art')], default='MEM', max_length=3),
        ),
    ]
