# Generated by Django 2.0.6 on 2018-12-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0008_auto_20181209_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='sender',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MEM', 'Meme'), ('POL', 'Politics'), ('SPT', 'Sport'), ('ART', 'Art'), ('MUS', 'Music')], default='MEM', max_length=3),
        ),
    ]
