# Generated by Django 2.0.6 on 2019-01-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0011_event_thumb_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdata',
            old_name='text',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='file',
        ),
        migrations.AlterField(
            model_name='event',
            name='accepted_by',
            field=models.IntegerField(default=-1),
        ),
    ]
