# Generated by Django 2.0.6 on 2019-01-03 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0014_auto_20190103_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reject_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='rejected_by',
            field=models.IntegerField(default=-1),
        ),
    ]
