# Generated by Django 2.0.6 on 2019-01-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0015_auto_20190103_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
