# Generated by Django 2.0.3 on 2019-01-18 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0017_auto_20190112_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='accept_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='reject_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
