# Generated by Django 2.0.3 on 2019-01-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0018_auto_20190119_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='publish_date',
        ),
    ]
