# Generated by Django 2.0.3 on 2019-01-18 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0021_remove_event_reject_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reject_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
