# Generated by Django 2.0.3 on 2019-01-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0022_event_reject_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='accept_date',
        ),
    ]
