# Generated by Django 2.0.3 on 2019-02-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_events', '0027_event_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MEM', 'Meme'), ('WOR', 'World'), ('SPT', 'Sport'), ('ART', 'Art'), ('MUS', 'Music'), ('SCI', 'Science'), ('GAM', 'Games'), ('MDA', 'Media')], default='MEM', max_length=3),
        ),
    ]
