# Generated by Django 2.0.6 on 2018-12-08 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('email_is_confirmed', models.BooleanField(default=False)),
                ('email_confirm_code', models.CharField(max_length=50)),
                ('password_reset_code', models.CharField(default=0, max_length=50)),
                ('status', models.CharField(default='User of SavesPlace', max_length=50)),
                ('staff_level', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('reg_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
