# Generated by Django 2.0.6 on 2018-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_users', '0004_auto_20181208_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='jwt_secret',
            field=models.FloatField(default=0.4676051778379161),
        ),
    ]
