# Generated by Django 2.0.6 on 2018-12-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_users', '0005_auto_20181208_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='jwt_secret',
            field=models.FloatField(default=0.48718511703200007),
        ),
    ]
