# Generated by Django 2.0.6 on 2018-12-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_users', '0006_auto_20181208_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='jwt_secret',
            field=models.FloatField(default=0.2511707094923019),
        ),
    ]
