# Generated by Django 2.0.6 on 2018-12-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_users', '0008_auto_20181208_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='jwt_secret',
            field=models.FloatField(default=0.28675604682184674),
        ),
    ]
