# Generated by Django 2.0.6 on 2018-12-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_users', '0015_auto_20181208_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.AlterField(
            model_name='account',
            name='jwt_secret',
            field=models.FloatField(default=0.22523716983314424),
        ),
    ]
