# Generated by Django 2.0.6 on 2018-12-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_users', '0016_auto_20181209_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='jwt_secret',
            field=models.FloatField(default=0.6646139284897992),
        ),
    ]
