# Generated by Django 2.0.6 on 2018-12-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_users', '0017_auto_20181209_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='jwt_secret',
            field=models.FloatField(default=0.156),
        ),
    ]
