# Generated by Django 2.0.6 on 2018-12-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_users', '0018_auto_20181209_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
