# Generated by Django 2.0.6 on 2018-12-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_users', '0019_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.IntegerField(default=1),
        ),
    ]
