# Generated by Django 2.0.3 on 2019-01-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_users', '0022_account_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email_confirm_code',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='password_reset_code',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='User of SavesPlace', max_length=70),
        ),
    ]
